site_name: OpenQuestion
google_analytics:
  - 259466481
  - auto

nav:
    - Home: index.md
    - Survey Development: survey_dev.md
    - Widgets: widgets.md
    - Settings: settings.md
    - Installation: installation.md
    - Advanced: advanced.md
    - FAQ: faq.md

repo_name: <i class="fa fa-github"></i> Github
repo_url: https://github.com/Alcampopiano/OpenQuestion
edit_uri: ""
theme:
  logo: img/logow.png
  favicon: img/logob.png
  name: material
  palette:
    primary: black
    accent: red
copyright: "OpenQuestion is licensed under the <a href='https://github.com/Alcampopiano/OpenQuestion/blob/master/LICENSE'>BSD 3-Clause license"

markdown_extensions:
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_css:
  - stylesheets/al_extra.css
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML